### ISSUE TITLE
ci.py doesn't work on the release branch

### ISSUE THREAD

**Issue by mr-c** [common-workflow-library/bio-cwl-tools#34]
```
$ python ci.py

fatal: ambiguous argument 'release..FETCH_HEAD': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:

'git <command> [<revision>...] -- [<file>...]'

Traceback (most recent call last):

  File "ci.py", line 9, in <module>

    changed_files = check_output("git --no-pager diff --name-status release..FETCH_HEAD", shell=True)

  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 389, in check_output

    **kwargs).stdout

  File "/opt/python/3.7.1/lib/python3.7/subprocess.py", line 481, in run

    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command 'git --no-pager diff --name-status release..FETCH_HEAD' returned non-zero exit status 128.
```

https://travis-ci.com/common-workflow-library/bio-cwl-tools/jobs/248764797

**Comment by medcelerate** [comment]
Working on a fix to check the branch
